[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "hypercorn main:app --bind 0.0.0.0:5000"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[nixpacksConfig]
platformTarget = "linux"

[packages]
tesseract = "latest"
ffmpeg = "latest"
poppler-utils = "latest"

[database]
engine = "POSTGRESQL"

[[ports]]
port = 5000
