[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacksConfig]
platformTarget = "linux"

[packages]
tesseract = "latest"
ffmpeg = "latest"
poppler-utils = "latest"

[database]
engine = "POSTGRESQL"

[[ports]]
port = 5000
